before_install:
  - brew update
  - brew install gcc || brew link --overwrite gcc
  - brew upgrade
  - brew outdated xctool || brew upgrade xctool
  - gem install cocoapods
  - pod setup
osx_image: xcode11.3
language: objective-c
xcode_project: Example_Swift/Example_Swift.xcworkspace
xcode_scheme: Example_Swift
xcode_sdk: iphonesimulator
script:
  - xcodebuild -project Example_Swift.xcodeproj -scheme Example_Swift -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.3' build test
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Example_Swift' -t 592f3d0c-a304-44a1-b99e-5ea37f78ce9d
