language: objective-c
osx_image: xcode8.3

script: xcodebuild clean && xcodebuild build -sdk iphonesimulator10.1 -project Example_Swift/Example_Swift.xcodeproj -scheme Example_Swift CODE_SIGNING_REQUIRED=NO